external_data_config:
  external_data_csv: data/external/WineQT.csv

raw_data_config: 
  raw_data_csv: data/raw/train.csv
  model_var: ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']
  train_test_split_ratio: 0.3
  target: quality
  random_state: 111
  new_train_data_csv: data/raw/train_new.csv

processed_data_config:
  train_data_csv: data/processed/wine_train.csv
  test_data_csv:  data/processed/wine_test.csv

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: 'qa_wine_model'
  run_name: random_forest
  registered_model_name: random_forest_model
  remote_server_uri: http://0.0.0.0:1234
 
random_forest: 
  max_depth: 15
  n_estimators: 45

model_dir: models/model.joblib

model_webapp_dir: webapp/model_webapp_dir/model.joblib

model_monitor:
  target_col_name: quality
  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html